const a=document.getElementById("song");
function enter(){document.getElementById("intro").classList.add("out");a.play().catch(()=>{});burst(35)}
function toggleMusic(){if(a.paused){a.play();musicText.textContent="Pause “Something About You”"}else{a.pause();musicText.textContent="Play “Something About You”"}}
const messages=["Your smile is one of those things I could see a thousand times and still stop for it.","Your laugh is one of my favorite sounds in the universe. I hope you never stop giving me reasons to hear it.","I love hearing about your day. Even the smallest details matter to me because they are pieces of your world.","Your softness and warmth make me feel loved in a way I cannot properly explain.","I will never forget your beautiful journey — everything you've lived through helped make you the person I love today.","After everything, I still choose you. Not because it is always easy, but because you are worth choosing, Frederika."];function reason(i){document.getElementById("reason").textContent=messages[i];burst(8)}
function show(t,b){document.getElementById("mt").textContent=t;document.getElementById("mb").textContent=b;document.getElementById("modal").classList.remove("hidden");burst(35)}
function surprise(){show("For Frederika ♡","If you are reading this, you found the little world I made for you. I hope every scroll reminds you that I am grateful a random TikTok reply led me back to you. Happy first year, my love. I choose you.");}
function forever(){show("And this is my favorite part.","The website ends here. Our story doesn't. There are places we haven't visited, photos we haven't taken, hugs we haven't had, and ordinary days we haven't shared yet. I want them with you, Frederika.");}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function burst(n){for(let i=0;i<n;i++){let e=document.createElement("span");e.className="float";e.textContent=["♡","♥","✦","❤"][Math.floor(Math.random()*4)];e.style.left=Math.random()*100+"vw";e.style.top=(70+Math.random()*30)+"vh";e.style.animationDuration=3+Math.random()*4+"s";document.body.appendChild(e);setTimeout(()=>e.remove(),8000)}}
