const audio=document.getElementById("song"),intro=document.getElementById("intro"),progress=document.getElementById("progress"),lightbox=document.getElementById("lightbox"),lightboxImg=document.getElementById("lightboxImg"),lightboxCaption=document.getElementById("lightboxCaption"),modal=document.getElementById("modal"),letterOverlay=document.getElementById("letterOverlay");
const messages=["Your smile is one of those things I could see a thousand times and still stop for it.","Your laugh is one of my favorite sounds in the universe. I hope you never stop giving me reasons to hear it.","I love hearing about your day. Even the smallest details matter to me because they are pieces of your world.","Your softness and warmth make me feel loved in a way I cannot properly explain.","I will never forget your beautiful journey — everything you've lived through helped make you the person I love today.","After everything, I still choose you. Not because it is always easy, but because you are worth choosing, Frederika."];
function burst(n){for(let i=0;i<n;i++){const e=document.createElement("span");e.className="float";e.textContent=["♡","♥","✦","❤"][Math.floor(Math.random()*4)];e.style.left=Math.random()*100+"vw";e.style.top=(70+Math.random()*30)+"vh";e.style.fontSize=12+Math.random()*18+"px";e.style.animationDuration=3+Math.random()*4+"s";document.body.appendChild(e);setTimeout(()=>e.remove(),8000)}}
async function enter(){intro.classList.add("out");try{await audio.play();document.getElementById("musicText").textContent='Pause “Something About You”'}catch(e){}burst(35)}
async function toggleMusic(){const t=document.getElementById("musicText");if(audio.paused){try{await audio.play();t.textContent='Pause “Something About You”'}catch(e){t.textContent='Tap again to play “Something About You”'}}else{audio.pause();t.textContent='Play “Something About You”'}}
function showModal(t,b){document.getElementById("mt").textContent=t;document.getElementById("mb").textContent=b;modal.classList.remove("hidden");burst(35)}function closeModal(){modal.classList.add("hidden")}
function openLightbox(fig){const img=fig.querySelector("img");if(!img||!img.getAttribute("src"))return;lightboxImg.src=img.getAttribute("src");lightboxImg.alt=img.alt||"";lightboxCaption.textContent=fig.querySelector("figcaption")?.textContent||"";lightbox.classList.remove("hidden");document.body.style.overflow="hidden"}
function closeLightbox(){lightbox.classList.add("hidden");lightboxImg.removeAttribute("src");lightboxImg.alt="";lightboxCaption.textContent="";document.body.style.overflow=""}
function openLetter(){letterOverlay.classList.remove("hidden");document.body.style.overflow="hidden";burst(22)}function closeLetter(){letterOverlay.classList.add("hidden");document.body.style.overflow=""}
document.getElementById("enterBtn").addEventListener("click",enter);document.getElementById("musicBtn").addEventListener("click",toggleMusic);document.getElementById("surpriseBtn").addEventListener("click",()=>showModal("For Frederika ♡","If you are reading this, you found the little world I made for you. I hope every scroll reminds you that I am grateful a random TikTok reply led me back to you. Happy first year, my love. I choose you."));document.getElementById("foreverBtn").addEventListener("click",()=>showModal("And this is my favorite part.","The website ends here. Our story doesn't. There are places we haven't visited, photos we haven't taken, hugs we haven't had, and ordinary days we haven't shared yet. I want them with you, Frederika."));document.getElementById("modalClose").addEventListener("click",closeModal);document.getElementById("modalOk").addEventListener("click",closeModal);document.getElementById("lightboxClose").addEventListener("click",closeLightbox);
document.querySelectorAll(".photo-card").forEach(f=>f.addEventListener("click",()=>openLightbox(f)));lightbox.addEventListener("click",e=>{if(e.target===lightbox)closeLightbox()});
document.querySelectorAll("[data-reason]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-reason]").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("reason").textContent=messages[Number(b.dataset.reason)];burst(8)}));
document.getElementById("catStage").addEventListener("click",openLetter);document.getElementById("catHint").addEventListener("click",openLetter);document.getElementById("catStage").addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openLetter()}});document.getElementById("letterClose").addEventListener("click",closeLetter);letterOverlay.addEventListener("click",e=>{if(e.target.classList.contains("letter-backdrop"))closeLetter()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeLightbox();closeModal();closeLetter()}});window.addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=(max>0?scrollY/max*100:0)+"%"});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>observer.observe(e));
document.addEventListener("pointermove",e=>{const h=document.getElementById("cursorHeart");h.style.left=e.clientX+"px";h.style.top=e.clientY+"px";h.style.opacity=".55"});document.addEventListener("pointerdown",e=>{if(e.target.closest("button,a"))return;const h=document.getElementById("cursorHeart");h.textContent=Math.random()>.5?"♡":"✦";h.style.opacity="1";setTimeout(()=>h.style.opacity=".55",180)});
